In [22]:
import pandas as pd
import numpy as np
import re

df=pd.read_excel('D:/DataScience/Advent/Day4.xlsx', header=None,skip_blank_lines=False)

df_num=df.to_numpy()
Sep=np.argwhere(pd.isnull(df_num)); 
Sep1=Sep[:,0]+1
Sep2=Sep[:,0]

Sep1=np.insert(Sep1,0,0)
Sep2=np.append(Sep2,len(df_num))

df_list=list(df.values.flatten())

Num=len(Sep1)
df_person=list();

i=0;
for i in range(0,Num):
    combine_information=''
    j=Sep1[i];
    for j in range(Sep1[i],Sep2[i]):        
        combine_information=combine_information+df_list[j]+' '
    df_person.append(combine_information)

In [23]:

Keys=['byr','iyr','eyr','hgt','hcl','ecl','pid']

i=0;num=0;id=[];
for i in range(0,len(df_person)):
    x=df_person[i]
    j=0
    Flag=100
    for j in range(0,len(Keys)):
        if x.find(Keys[j])==-1:
            flag=-1
        else:
            flag=1        
        Flag=Flag+flag;
    
    if Flag==107:
        num=num+1
        id.append(i)

print(num)
print(id)

190
[0, 1, 2, 3, 4, 5, 6, 9, 10, 11, 12, 13, 14, 15, 16, 18, 19, 21, 22, 23, 24, 25, 26, 27, 28, 30, 33, 34, 35, 36, 37, 38, 39, 40, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 58, 60, 61, 64, 65, 66, 68, 72, 73, 76, 77, 78, 79, 81, 82, 83, 85, 86, 87, 88, 90, 91, 92, 93, 96, 97, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 119, 120, 121, 123, 124, 125, 126, 127, 128, 130, 131, 132, 133, 134, 137, 139, 140, 142, 143, 146, 148, 149, 150, 151, 152, 153, 154, 156, 157, 158, 159, 161, 165, 166, 167, 168, 169, 170, 172, 175, 178, 179, 180, 181, 182, 183, 186, 187, 189, 190, 191, 193, 194, 196, 197, 199, 200, 201, 202, 204, 206, 207, 208, 211, 212, 213, 214, 215, 216, 217, 220, 221, 222, 223, 225, 226, 227, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 240, 241, 244, 245, 246, 247, 249, 250, 251]

In [106]:
Dic=[]
for iper in id:
    x=df_person[iper]
    x=x.split(' ')
    list_key=[];
    list_value=[];
    for j in range (0,len(x)-1):
        y=x[j]   
        y=y.split(":")
        list_key.append(y[0])
        list_value.append(y[1])
    dic=dict(zip(list_key,list_value ) )
    Dic.append(dic)
    
df1=pd.DataFrame(Dic)
df1=df1.drop('cid',axis=1)
df1.head()

    iyr        pid   eyr      hcl      ecl   byr    hgt
0  1928  476113241  2039   a5ac0f  #25f8d2  2027    190
1  2013  920076943  2026  #fffffd      hzl  1929  168cm
2  2011  328412891  2023  #6b5442      brn  1948  156cm
3  2019  674907993  2020  #602927      amb  1950  189cm
4  2015  473630095  2022  #341e13      hzl  1976  178cm

In [134]:
df1['byr']=df1['byr'].apply(int)
df1['iyr']=df1['iyr'].apply(int)
df1['eyr']=df1['eyr'].apply(int)

df1=df1[df1.byr>=1920]
df1=df1[df1.byr<=2002]

df1=df1[df1.iyr>=2010]
df1=df1[df1.iyr<=2020]

df1=df1[df1.eyr>=2020]
df1=df1[df1.eyr<=2030]

filter_ecl=['amb','blu','brn','gry','grn','hzl','oth']
df1=df1[df1.ecl.isin(filter_ecl)]

df1=df1[df1.hcl.str.contains('^\\#')]
df1=df1[df1.hcl.str.len()==7]

df1=df1[df1.pid.str.len()==9]
df1['pid']=df1['pid'].apply(int)
df1=df1[df1.pid>=0]
df1=df1[df1.pid<=999999999]


df_cm=df1[df1.hgt.str.contains('cm')]
df_in=df1[df1.hgt.str.contains('in')]
df_cm['hgt'] = df_cm['hgt'].map(lambda x: str(x)[:-2])
df_in['hgt'] = df_in['hgt'].map(lambda x: str(x)[:-2])

df_cm.hgt=df_cm.hgt.apply(int)
df_in.hgt=df_in.hgt.apply(int)

df_cm=df_cm[df_cm.hgt>=150]
df_cm=df_cm[df_cm.hgt<=193]

df_in=df_in[df_in.hgt>=59]
df_in=df_in[df_in.hgt<=76]

len(df_cm)+len(df_in)

124